### ISSUE TITLE
Keys ending with /

### ISSUE THREAD

**Issue by dkumor** [localForage/localForage-startsWith#1]
startsWith seems not to return any results if the search parameter ends with '/'. I have keys of the type `{a}/{b}`, and searching for `{a}` works correctly, `{a}/{first letter of b}` also works, but `{a}/` does not return any results.

This is on chrome 50.0.2661.102, 64 bit. I didn't do further testing and worked around this (deadline), so I don't know exactly why it happens, and have not tried reproducing in other browsers.

I am using localForage `1.4.1`, localforage-startswith `1.2.0`

**Comment by thgreasi** [comment]
Thanks for reporting (+ while having a deadline). I will try to investigate
during the weekend.

> ## 
> 
> _Thodoris Greasidis_
> Computer, Networking &
> Communications Engineer

**Comment by thgreasi** [comment]
Hi there, just found some time to take a look at this.
Strangely enough, I created a [codepen example](http://codepen.io/thgreasi/pen/BzaRBo) and I wasn't able to reproduce this issue. Tested all drivers on FF and Chrome with localforage v1.4.
Please fork the codepen and re-open if you can find the case that causes the issue.

**Comment by dkumor** [comment]
Thanks - not sure what is wrong with my setup, I'll try to find the issue.
