### ISSUE TITLE
[Feature Request] keysStartsWith option

### ISSUE THREAD

**Issue by timfish** [localForage/localForage-startsWith#3]
Many thanks for this, it's working great for my current setup!

However, some of my objects are rather large and it would be great to be able to get just the keys first and decide which ones I want to pull from storage after.

**Comment by thgreasi** [comment]
That's a good idea. I will check whether there is an efficient way to check
whether a key exists without retrieving the value. Obviously keys with null
values will be reported as existing. Is that OK?

> --
*Thodoris Greasidis*

**Comment by timfish** [comment]
To be honest, I had only really thought about from an IndexedDb perspective where I know there is a very efficient way to do it.

From previously using [dexie](https://github.com/dfahlander/Dexie.js), it could query the index with [startsWith](https://github.com/dfahlander/Dexie.js/wiki/WhereClause.startsWith()) which returned a [Collection](https://github.com/dfahlander/Dexie.js/wiki/Collection) which didn't hold any of the objects. You had to `each()` or `toArray` for it to fetch the objects out of the db.

**Comment by thgreasi** [comment]
Hi there. I have completed an initial intention and a branch for this. Although websql and localstorage benefit from not being required to retrieve and deserialize the associate value of each key, IndexedDB retrieves the whole object for each key.
Am I missing something, since you mentioned that:
> I had only really thought about from an IndexedDb perspective where I know there is a very efficient way to do it.

**Comment by timfish** [comment]
You can do the range query on the key which is very efficient.
```
IDBKeyRange.bound(prefix, prefix + 'uffff', false, false)
```
But I think yes, you're right. You still have to go through the full results with the cursor.

**Comment by thgreasi** [comment]
That's [what we are already doing](https://github.com/localForage/localForage-startsWith/blob/5e0f1dfc2db678cca2bdb899a6e1bcaea012191c/lib/startswith-indexeddb.js#L13-L16).
Here is the [keysStartingWith branch](https://github.com/localForage/localForage-startsWith/tree/keysStartingWith).
Should we include that method even though there is no benefit for IndexedDB?

**Comment by timfish** [comment]
I suppose there are cases where `IDBObjectStore.getAllKeys()` and manually filtering will be fastest and cases where `IDBKeyRange.bound` and then pulling the keys from the cursor results could be faster. It will depend on the size of the db, the size of data and the range of keys requested.

For most cases `IDBObjectStore.getAllKeys()` and filtering will be faster.

**Comment by thgreasi** [comment]
To be honest I forgot about `getAllKeys()`.
I just pushed some new commits to #4 that indicate some performance benefits over the plain `startsWith()`.
I will probably write a few line to the README and cut a release tomorrow.

Thanks for the hint!
