### ISSUE TITLE
Webpack import: startsWith is not a function

### ISSUE THREAD

**Issue by morkro** [localForage/localForage-startsWith#5]
Hey 👋 

I am using this module for quite some time now, but after updating a couple of dependencies (Webpack, and Vue.js related) I am stuck with the following error:

> TypeError: __WEBPACK_IMPORTED_MODULE_0_localforage___default.a.startsWith is not a function

I use `localforage@^1.5.0` and `localforage-startswith@^1.3.0` in a Vue.js project, with a Webpack setup. I am honestly not sure if this is an issue with this module, Webpack, or something else. 

So far, I have used the module always as follows in my main entry point and it worked without any issues:

```js
import localforage from 'localforage'
import 'localforage-startswith'
```

Is this is an issue with Webpack (maybe `vue-loader`) or something else? I am a bit lost at this point and trying to debug this for quite some time now. 😅

**Comment by thgreasi** [comment]
Is this in typescript?

**Comment by morkro** [comment]
Nope. JavaScript, but a Vue.js environment.

**Comment by thgreasi** [comment]
This seems a webpack issue to me, it seems that some static analysis of the imports takes place there.
What I suggest to TypeScript users and should also work here is to do something like this:
```js
import localForage from 'localforage'
import { extendPrototype } from 'localforage-startswith'
const localforage = extendPrototype(localForage)
```
That method will do nothing extra in your case, since the method should already be there.

**Comment by morkro** [comment]
@thgreasi thank you so much, that solved the issue for me.

What do you think about adding this bit of information to the README? It's really helpful and I guess other developers might have the same issue at some point. I am happy to submit a PR for this.

**Comment by thgreasi** [comment]
I will try to also add some typing during the weekend.
There is a respective TypeScript comment on https://github.com/localForage/localForage-observable#typescript that you can use as a basis.

I'm just not really sure how we should explain your issue. Maybe we can add the TypeScript section and then add in the `installation` section something like:
> **Note**: In case that your js packager doesn't automatically make the `.startsWith()` available to `localforage` please use the `extendPrototype()` method as demonstrated in the the Typescript instructions.

**Comment by morkro** [comment]
Maybe something like this?

> ## Known issues with module bundlers
> In some cases `.startsWith()` might not automatically be made available to the `localforage` object on import. In this case, import the provided `extendPrototype()` method and extend it manually:
>
>```js
>import localforage from 'localforage';
>import { extendPrototype } from 'localforage-startswith';
>
>extendPrototype(localforage);
>
>// Keep using localForage as usual.
>```

**Comment by thgreasi** [comment]
👍

**Comment by diemanmanly** [comment]
you have to install localforage-startswith packet
npm install --save localforage-startswith
